AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A lambda to upload to S3
Parameters:
  Environment:
    Type: String
    AllowedValues:
    - dev
    - staging
    - prod
  LambdaName:
    Type: String
    Default: medium-example
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Join:
        - '-'
        - - Ref: LambdaName
          - Ref: Environment              
      Handler: main.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          EXAMPLE_S3_BUCKET:
            Ref: ExampleS3Bucket
      MemorySize: 256
      Timeout: 600 
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: rate(3 hours)
      Tracing: Active
      Policies:
        - Statement:
          - Action:
            - s3:PutObject
            Effect: Allow
            Resource:
              Fn::Join:
              - /
              - - Fn::GetAtt:
                  - ExampleS3Bucket
                  - Arn
                - '*'
  LambdaFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: LambdaFunction
    Properties:
      LogGroupName:
        Fn::Join:
        - ''
        - - /aws/lambda/
          - Ref: LambdaName
          - '-'
          - Ref: Environment
      RetentionInDays: 14
  ExampleS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Join:
        - '-'
        - - medium-example
          - Ref: Environment
Outputs:
  LambdaArn:
    Value:
      Fn::GetAtt:
      - LambdaFunction
      - Arn
